Add procedure context
maticnetwork/miden pull request #111
Opened 2022-02-14 08:09 UTC by tnachen

Addresses #106

2022-02-14 18:08 UTC, bobbinth requested changes
Thank you! Looks good. I left some inline comments.

The biggest thing I'm still tying to think through is whether it would be possible to keep `Operation` as `Copy` as I'm not sure what could performance implications of getting rid of `Copy` be.

2022-02-14 18:08 UTC, bobbinth commented on core/src/operations/proc.rs
> +/// Stores procedure information
nit: could we say "Contains procedure metadata (without procedure body)"?

2022-02-14 22:25 UTC, tnachen commented on core/src/operations/proc.rs
> +        write!(f, "proc.{}.{}", self.name, self.locals)?;
ah yes, sorry I forgot about this

2022-02-15 21:08 UTC, bobbinth requested changes
Thank you! A few small comments inline.

A couple of additional things:
1. Could you rebase from the latest `next`? There was one small refactoring which may not compile with `Operation` not being `Copy`.
2. There is one piece missing: we need to modify the procedure parser to actually inserted `ProcStart` and `ProcEnd` operations into the program during parsing.

2022-02-15 21:08 UTC, bobbinth commented on processor/src/operations/mod.rs
> +            Operation::Debug(options) => self.op_debug(*options)?,
Should we pass debug options by reference here?

2022-08-08 21:12 UTC, bobbinth commented
Superseded by #315

2022-08-08 21:12 UTC, closed without merging