[Draft] - add selector constraint for bitwise_pow2 aux_table
maticnetwork/miden pull request #219
Opened 2022-05-24 11:21 UTC by 0xKanekiKen

This PR address #206.

New constraints have been added to bitwise_pow2 aux_table to assert that the selector values remain same throughout the cycle.

2022-05-26 14:10 UTC, grjte requested changes
The constraint changes look great, thank you! I've left a few comments inline, and I have a few more general comments:

1. There were several changes to "pub" in the `bitwise/tests.rs` file that I don't think are necessary. Can you please revisit these?
2. The new `bitwise_pow2/tests.rs` module should be declared in the `bitwise_pow2/mod.rs` file. Otherwise, they won't be run.
3. nit: It would be good to rebase the latest commit that removes debug comments so it's squashed into the "feat" commit, since we don't need those lines in the git history

2022-05-26 16:02 UTC, 0xKanekiKen commented on air/src/aux_table/bitwise_pow2/mod.rs
> +        *result = processor_flag * is_binary(frame.selector(idx))
Done

2022-05-26 16:03 UTC, 0xKanekiKen commented on air/src/aux_table/bitwise_pow2/mod.rs
> +    // except 0 should match value of selector of row 0.
I've updated the comment in the latest PR. Please see [b2c89e6](https://github.com/maticnetwork/miden/pull/219/commits/b2c89e6f0ae13a927a2e927d6bf2c059f394272c)

2022-05-26 16:03 UTC, 0xKanekiKen commented on air/src/aux_table/bitwise_pow2/mod.rs
> +        *result = processor_flag * (k1 * (frame.selector(idx) - frame.selector_next(idx)));
Done

2022-05-26 16:07 UTC, 0xKanekiKen commented on air/src/aux_table/bitwise_pow2/tests.rs
> +pub const NUM_CONSTRAINTS: usize = 42;
Thanks. I used the alternative one in the latest PR.

Please see [b3d413e](https://github.com/maticnetwork/miden/pull/219/commits/b3d413eab9f6d1568b30d5c69b9de758b155736e).

2022-05-26 16:11 UTC, 0xKanekiKen commented on air/src/aux_table/bitwise_pow2/tests.rs
> +    EvaluationFrame::<Felt>::from_rows(current_row, next_row)
I wanted to try something with current_row and next_row earlier but yes, I agree with you that we can use the frame directly. I've reverted it back to the original function in the latest PR.

2022-05-26 16:11 UTC, 0xKanekiKen commented on air/src/aux_table/bitwise_pow2/tests.rs
> +/// in bitwise and pow2 tests respectively.
I've removed the last line in the latest PR. Thanks.

2022-05-26 16:11 UTC, 0xKanekiKen commented on air/src/aux_table/bitwise_pow2/bitwise/tests.rs
> +    )
Actioned. Thanks.

2022-05-30 13:16 UTC, grjte requested changes
Looks good, thanks! I left 2 very minor things inline related to docs/comments.

2022-05-30 13:16 UTC, grjte commented on air/src/aux_table/bitwise_pow2/tests.rs
> +/// bitwise(14) + pow2(24)
This comment should also be updated to remove the numbers, now that the the constant is not being hardcoded.

2022-05-30 13:16 UTC, grjte commented on docs/src/design/aux_table/main.md
> +The constraints must require that the selectors be binary and stays the same throughout the cycle:
minor nit: it should be "and stay the same throughout the cycle"

2022-06-02 15:27 UTC, 0xKanekiKen commented
Thanks for the review! I've actioned on the suggested changes.

2022-06-03 09:02 UTC, grjte commented
Looks good, thank you!

2022-06-03 09:03 UTC, merged

2022-06-03 09:08 UTC, grjte reviewed
Looks good!