Implement movupw parsing
maticnetwork/miden pull request #25
Opened 2021-12-27 05:56 UTC by tnachen

Implement movupw parsing

2021-12-27 06:56 UTC, bobbinth requested changes
Thank you! Looks good. I've added a couple of comment inline, and a couple more general comments:

1. Let's remove leading underscores from all variable names (leading underscores are used for unused variables only).
2. Let's add documentation comments similar to how we do for other implemented parsers.

2021-12-27 06:56 UTC, bobbinth commented on assembly/src/v1/parsers/stack_ops.rs
> +        _ => return Err(AssemblyError::extra_param(_op)),
The error returned form here should be created with `invalid_param()`.

2021-12-27 06:56 UTC, bobbinth commented on assembly/src/v1/parsers/stack_ops.rs
> +    if _op.num_parts() != 2 {
We should check here if `op.num_parts()` is less than 2. In such a case, we should return `missing_param()` error. Incases when `op.num_parts()` is greater than two, we should return `extra_param()` (as is done now).

2021-12-27 08:01 UTC, bobbinth requested changes
Thank you! A few more comments:

Let's combine the two match statements. A single statement could look as follows:
```Rust
match op.num_parts() {
    0..=1 => return Err(AssemblyError::missing_param(op)),
    2 => match op.parts()[1] {
        ...
    }
    _ => return Err(AssemblyError::extra_param(op)),
}
```

Also, carrying over from the previous review:
* Let's remove leading underscores from all variable names.
* Let's add documentation comments similar to how we do for other implemented parsers.

2021-12-28 05:24 UTC, bobbinth requested changes
Looks great! I left one minor nit in the comments. Also, could you make sure `rustfmt` tests pass? You can make sure rustfmt and clippy are happy  by running:

```
cargo fix --allow-staged --allow-dirty --all-targets --all-features && cargo fmt && cargo clippy  
```

The above should work on MacOS and Linux.

2021-12-28 05:24 UTC, bobbinth commented on assembly/src/v1/parsers/stack_ops.rs
> +/// Translates movupw assembly instruction to VM operations.
I'd prefer a slightly more expanded comment. Maybe something like:

```Rust
/// Translates movupw.x assembly instruction to VM operations.
///
/// Specifically:
/// * movupw.2 is translated into SWAPW SWAPW2
/// * movupw.3 is translated into SWAPW SWAPW2 SWAPW3
```

2021-12-29 03:36 UTC, tnachen commented
Ah, seems like it would be nice to have rustfmt run in a pre-commit hook

2021-12-29 19:45 UTC, bobbinth approved these changes
Everything looks great! Thank you!

2021-12-29 19:46 UTC, merged