New assembly instructions
maticnetwork/miden pull request #387
Opened 2022-09-06 16:25 UTC by OLUWAMUYIWA

## What
Added `assertz`, `u32wrapping_madd`, and `u32wrapping_add3` to assembly instructions.
Ref: #357 

Also updated the documentation to accommodate the new insructions.

2022-09-06 16:26 UTC, OLUWAMUYIWA commented
@bobbinth please check.

2022-09-06 19:07 UTC, bobbinth requested changes
Looks great! Thank you! I left a couple of very minor nit comments inline.

2022-09-06 19:07 UTC, bobbinth commented on docs/src/user_docs/assembly/field_operations.md
> +| assertz <br> - *(2 cycles)*       | [ a, ...] | [...]              | if $a = 0$, removes it from the stack, <br> Fails if $a \ne b$ |
minor nit: I'd probably put `assertz` above `assert_eq` in the table.

2022-09-06 19:07 UTC, bobbinth commented on assembly/src/parsers/field_ops.rs
> +pub(super) fn parse_assert_eqz(
minor nit: I'd probably name the function `parse_assertz` to keep it consistent with the instruction name.

2022-09-06 19:07 UTC, bobbinth commented on assembly/src/parsers/u32_ops.rs
> +    #[test]
very minor nit: I'd add a blank line above `#[test]`.

2022-09-07 10:00 UTC, OLUWAMUYIWA commented
@bobbinth, I made the changes you requested

2022-09-07 17:38 UTC, bobbinth approved these changes
All looks good! Thank you again!

2022-09-07 17:39 UTC, merged