Implement syscall operation
maticnetwork/miden pull request #412
Opened 2022-09-22 06:36 UTC by bobbinth

This PR implements `SYSCALL` operation and associated assembly instruction.

2022-09-30 15:16 UTC, grjte requested changes
Thanks @bobbinth! Looks good to me overall, but I think it would be good to add a bit more about compiling kernel procedures to the inline docs

2022-09-30 16:15 UTC, bobbinth commented on core/src/program/blocks/call_block.rs
> +        // TODO: make hash computation different from regular call
I think this is a more general issue of how we compute hashes of nodes (we need to do something similar for differentiating between hashes of `JOIN` vs. `SPLIT` blocks). We'll address this as we migrate to a different version of Rescue hash function (probably not early than v0.4).

2022-10-03 12:44 UTC, grjte commented on core/src/program/blocks/call_block.rs
> +        // TODO: make hash computation different from regular call
Should that whole migration be captured as an issue then? (and just marked "on hold" for now)

2022-10-03 12:49 UTC, grjte approved these changes
Thanks @bobbinth ! I think the docs changes were helpful

2022-10-03 12:49 UTC, grjte commented on assembly/src/lib.rs
> +///   into a set of kernel procedures during instantiation. The programs complied using such
nit: There's a typo. It says "complied" instead of "compiled"

2022-10-03 19:08 UTC, merged