feat: stack overflow constraints
maticnetwork/miden pull request #426
Opened 2022-10-09 17:45 UTC by 0xKanekiKen

## Describe your changes
Introduce stack overflow air constraints to the VM. It doesn't include the overflow table multi-set constraints.

## Checklist before requesting a review
- Repo forked and branch created from `next` according to naming convention.
- Commit messages and codestyle follow [conventions](./CONTRIBUTING.md).
- Relevant issues are linked in the PR description.
- Tests added for new functionality.
- Documentation/comments updated according to changes.

2022-10-20 02:20 UTC, bobbinth requested changes
Looks good! Thank you! I left a few nits and small comments inline.

2022-10-20 02:20 UTC, bobbinth commented on air/src/stack/overflow/mod.rs
> +    let stack_last_next = frame.stack_item_next(15);
nit: I'd rename this to `last_stack_item_next`.

2022-10-20 02:20 UTC, bobbinth commented on air/src/stack/mod.rs
> +    fn stack_overflow_index_next(&self) -> E {
nit: I'd rename this to `stack_overflow_addr_next()`.

2022-10-20 22:04 UTC, 0xKanekiKen commented on air/src/stack/overflow/mod.rs
> +    7, 8, // constraint for stack overflow bookkeeping index, b1.
The docs needs fixing. $f_{shr}$ degree should be 6 instead of 7 [here](https://maticnetwork.github.io/miden/design/stack/main.html#air-constraints). I've updated the doc in the commit [f6097c3](https://github.com/maticnetwork/miden/pull/426/commits/f6097c3a12a7d101a80d31d63cd46ea1dfc11ae6).

2022-10-20 22:07 UTC, 0xKanekiKen commented on air/src/stack/overflow/mod.rs
> +    result[0] = no_shift_part + left_shift_part - right_shift_part + call_part;
As discussed, lets take this up again once the `syscall` PR gets merged.

2022-10-21 07:04 UTC, bobbinth approved these changes
All looks good! Thank you!

2022-10-21 07:04 UTC, merged