Add call & syscall blocks to the program MAST design docs
maticnetwork/miden pull request #554
Opened 2022-11-23 18:17 UTC by grjte

This PR updates the design documentation of the program MAST to include call and syscall blocks

2022-11-23 19:15 UTC, bobbinth requested changes
Looks good! Thank you! A few comments:

1. We should also update the "Program hash computation" section at the end of the file.
2. Minor nit: could we make sizes of the new images a bit smaller?
3. I'm wondering if we should provide additional details about what the VM does when executing `CALL` and `SYSCALL` blocks. For example:
  a. The VM first checks if we are already executing a `syscall` and fails if we do.
  b. The depth of the stack is set at 16.
  c. Upon return, the depth of the stack is checked to be 16, and if it is, the original stack depth is restored. Otherwise, an error happens.

2022-11-28 10:27 UTC, grjte commented
Thanks for your review @bobbinth. I've addressed the comments. Please let me know if there's anything else missing!

2022-11-28 19:35 UTC, bobbinth commented on docs/src/design/programs.md
> +2. Upon return, checks that the depth of the stack is 16. If so, the original stack depth is restored. Otherwise, an error occurs.
Here we also check if we are in a `syscall`. Executing a `call` block inside a `syscall` also results in an error.

2022-11-29 15:12 UTC, bobbinth approved these changes
All looks good! Thank you!

2022-11-29 15:12 UTC, merged